In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Daksh_Gururkul_IITG_May_2025/11_Projects/India Agriculture Crop Production.csv')
df.sample(5)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
317868,Madhya Pradesh,HARDA,Arhar/Tur,1999-00,Kharif,3022.0,Hectare,2979.0,Tonnes,0.985771
6690,Bihar,VAISHALI,Maize,2001-02,Summer,6421.0,Hectare,16387.0,Tonnes,2.552095
81925,Uttar Pradesh,BALLIA,Sweet potato,2005-06,Whole Year,19.0,Hectare,248.0,Tonnes,13.052632
986,Andhra Pradesh,CHITTOOR,Horse-gram,2002-03,Kharif,6941.0,Hectare,3679.0,Tonnes,0.530039
71058,Odisha,KHORDHA,Sesamum,2004-05,Autumn,1.0,Hectare,0.1,Tonnes,0.100000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

# Unique count and values for Crops , Districts

In [4]:
unique_crop_list = df['Crop'].unique()

In [5]:
print(f'Total number of unique crops in India is {len(unique_crop_list)}\nThey are: \n{unique_crop_list}')

Total number of unique crops in India is 57
They are:
['Arecanut' 'Banana' 'Black pepper' 'Cashewnut' 'Coconut' 'Dry chillies'
 'Ginger' 'Other Kharif pulses' 'other oilseeds' 'Rice' 'Sugarcane'
 'Sweet potato' 'Arhar/Tur' 'Bajra' 'Castor seed' 'Coriander'
 'Cotton(lint)' 'Gram' 'Groundnut' 'Horse-gram' 'Jowar' 'Linseed' 'Maize'
 'Mesta' 'Moong(Green Gram)' 'Niger seed' 'Onion' 'Other Rabi pulses'
 'Potato' 'Ragi' 'Rapeseed &Mustard' 'Safflower' 'Sesamum' 'Small millets'
 'Soyabean' 'Sunflower' 'Tapioca' 'Tobacco' 'Turmeric' 'Urad' 'Wheat'
 'Oilseeds total' 'Jute' 'Masoor' 'Peas & beans (Pulses)' 'Barley'
 'Garlic' 'Khesari' 'Sannhamp' 'Guar seed' 'Moth' 'Cardamom'
 'Other Cereals' 'Cowpea(Lobia)' 'Dry Ginger' 'Other Summer Pulses' nan]

In [6]:
unique_district_list = df['District'].unique()
print(f'Total number of districts in India is {len(unique_district_list)}\nThey are: \n{unique_district_list}')

Total number of districts in India is 729
They are:
['NICOBARS' 'NORTH AND MIDDLE ANDAMAN' 'SOUTH ANDAMANS' 'ANANTAPUR'
 'EAST GODAVARI' 'KRISHNA' 'VIZIANAGARAM' 'WEST GODAVARI' 'ADILABAD'
 'CHITTOOR' 'GUNTUR' 'KADAPA' 'KARIMNAGAR' 'KHAMMAM' 'KURNOOL'
 'MAHBUBNAGAR' 'MEDAK' 'NALGONDA' 'NIZAMABAD' 'PRAKASAM' 'RANGAREDDI'
 'SPSR NELLORE' 'SRIKAKULAM' 'VISAKHAPATANAM' 'WARANGAL' 'CHANGLANG'
 'DIBANG VALLEY' 'EAST KAMENG' 'EAST SIANG' 'KURUNG KUMEY' 'LOHIT'
 'LOWER DIBANG VALLEY' 'LOWER SUBANSIRI' 'PAPUM PARE' 'TAWANG' 'TIRAP'
 'UPPER SIANG' 'UPPER SUBANSIRI' 'WEST KAMENG' 'WEST SIANG' 'BARPETA'
 'BONGAIGAON' 'CACHAR' 'DARRANG' 'DHEMAJI' 'DHUBRI' 'DIBRUGARH'
 'DIMA HASAO' 'GOALPARA' 'GOLAGHAT' 'HAILAKANDI' 'JORHAT' 'KAMRUP'
 'KARBI ANGLONG' 'KARIMGANJ' 'KOKRAJHAR' 'LAKHIMPUR' 'MARIGAON' 'NAGAON'
 'NALBARI' 'SIVASAGAR' 'SONITPUR' 'TINSUKIA' 'ARARIA' 'ARWAL' 'AURANGABAD'
 'BANKA' 'BEGUSARAI' 'BHAGALPUR' 'BHOJPUR' 'BUXAR' 'DARBHANGA' 'GAYA'
 'GOPALGANJ' 'JAMUI' 'JEHANABAD' 'KAIMUR (BHABUA)' 'KATIHAR' 'KHAGARIA'
 'KISHANGANJ' 'LAKHISARAI' 'MADHEPURA' 'MADHUBANI' 'MUNGER' 'MUZAFFARPUR'
 'NALANDA' 'NAWADA' 'PASHCHIM CHAMPARAN' 'PATNA' 'PURBI CHAMPARAN'
 'PURNIA' 'ROHTAS' 'SAHARSA' 'SAMASTIPUR' 'SARAN' 'SHEIKHPURA' 'SHEOHAR'
 'SITAMARHI' 'SIWAN' 'SUPAUL' 'VAISHALI' 'CHANDIGARH' 'BASTAR' 'BILASPUR'
 'DANTEWADA' 'DHAMTARI' 'DURG' 'JANJGIR-CHAMPA' 'JASHPUR' 'KABIRDHAM'
 'KANKER' 'KORBA' 'KOREA' 'MAHASAMUND' 'RAIGARH' 'RAIPUR' 'RAJNANDGAON'
 'SURGUJA' 'DADRA AND NAGAR HAVELI' 'Daman and Diu' 'Delhi' 'Goa'
 'AHMADABAD' 'AMRELI' 'ANAND' 'BANAS KANTHA' 'BHARUCH' 'BHAVNAGAR' 'DANG'
 'DOHAD' 'GANDHINAGAR' 'JAMNAGAR' 'JUNAGADH' 'KACHCHH' 'KHEDA' 'MAHESANA'
 'NARMADA' 'NAVSARI' 'PANCH MAHALS' 'PATAN' 'PORBANDAR' 'RAJKOT'
 'SABAR KANTHA' 'SURAT' 'SURENDRANAGAR' 'VADODARA' 'VALSAD' 'AMBALA'
 'BHIWANI' 'FARIDABAD' 'FATEHABAD' 'GURGAON' 'HISAR' 'JHAJJAR' 'JIND'
 'KAITHAL' 'KARNAL' 'KURUKSHETRA' 'MAHENDRAGARH' 'PANCHKULA' 'PANIPAT'
 'REWARI' 'ROHTAK' 'SIRSA' 'SONIPAT' 'YAMUNANAGAR' 'KANGRA' 'KULLU'
 'MANDI' 'SHIMLA' 'SOLAN' 'UNA' 'CHAMBA' 'HAMIRPUR' 'SIRMAUR' 'KINNAUR'
 'LAHUL AND SPITI' 'DODA' 'JAMMU' 'KATHUA' 'RAJAURI' 'UDHAMPUR' 'KARGIL'
 'LEH LADAKH' 'SRINAGAR' 'BADGAM' 'BARAMULLA' 'POONCH' 'PULWAMA'
 'ANANTNAG' 'KUPWARA' 'CHATRA' 'DUMKA' 'GARHWA' 'GODDA' 'GUMLA'
 'HAZARIBAGH' 'KODERMA' 'LATEHAR' 'LOHARDAGA' 'PAKUR' 'PALAMU' 'RANCHI'
 'SAHEBGANJ' 'SARAIKELA KHARSAWAN' 'SIMDEGA' 'WEST SINGHBHUM' 'BOKARO'
 'DEOGHAR' 'DHANBAD' 'EAST SINGHBUM' 'GIRIDIH' 'JAMTARA' 'BAGALKOT'
 'BANGALORE RURAL' 'BELGAUM' 'BELLARY' 'BENGALURU URBAN' 'CHAMARAJANAGAR'
 'CHIKMAGALUR' 'CHITRADURGA' 'DAKSHIN KANNAD' 'DAVANGERE' 'DHARWAD'
 'GADAG' 'HASSAN' 'HAVERI' 'KODAGU' 'KOLAR' 'MANDYA' 'MYSORE' 'SHIMOGA'
 'TUMKUR' 'UDUPI' 'UTTAR KANNAD' 'BIDAR' 'BIJAPUR' 'GULBARGA' 'KOPPAL'
 'RAICHUR' 'ALAPPUZHA' 'ERNAKULAM' 'IDUKKI' 'KANNUR' 'KASARAGOD' 'KOLLAM'
 'KOTTAYAM' 'KOZHIKODE' 'MALAPPURAM' 'PALAKKAD' 'PATHANAMTHITTA'
 'THIRUVANANTHAPURAM' 'THRISSUR' 'WAYANAD' 'ANUPPUR' 'ASHOKNAGAR'
 'BALAGHAT' 'BARWANI' 'BETUL' 'BHIND' 'BHOPAL' 'BURHANPUR' 'CHHATARPUR'
 'CHHINDWARA' 'DAMOH' 'DATIA' 'DEWAS' 'DHAR' 'DINDORI' 'GUNA' 'GWALIOR'
 'HARDA' 'HOSHANGABAD' 'INDORE' 'JABALPUR' 'JHABUA' 'KATNI' 'KHANDWA'
 'KHARGONE' 'MANDLA' 'MANDSAUR' 'MORENA' 'NARSINGHPUR' 'NEEMUCH' 'PANNA'
 'RAISEN' 'RAJGARH' 'RATLAM' 'REWA' 'SAGAR' 'SATNA' 'SEHORE' 'SEONI'
 'SHAHDOL' 'SHAJAPUR' 'SHEOPUR' 'SHIVPURI' 'SIDHI' 'TIKAMGARH' 'UJJAIN'
 'UMARIA' 'VIDISHA' 'AHMEDNAGAR' 'AKOLA' 'AMRAVATI' 'BEED' 'BHANDARA'
 'BULDHANA' 'CHANDRAPUR' 'DHULE' 'GADCHIROLI' 'GONDIA' 'HINGOLI' 'JALGAON'
 'JALNA' 'KOLHAPUR' 'LATUR' 'NAGPUR' 'NANDED' 'NANDURBAR' 'NASHIK'
 'OSMANABAD' 'PARBHANI' 'PUNE' 'RAIGAD' 'RATNAGIRI' 'SANGLI' 'SATARA'
 'SOLAPUR' 'THANE' 'WARDHA' 'WASHIM' 'YAVATMAL' 'SINDHUDURG' 'SENAPATI'
 'BISHNUPUR' 'CHANDEL' 'CHURACHANDPUR' 'IMPHAL EAST' 'IMPHAL WEST'
 'TAMENGLONG' 'THOUBAL' 'UKHRUL' 'EAST GARO HILLS' 'EAST JAINTIA HILLS'
 'EAST KHASI HILLS' 'RI BHOI' 'SOUTH GARO HILLS' 'WEST GARO HILLS'
 'WEST KHASI HILLS' 'AIZAWL' 'CHAMPHAI' 'KOLASIB' 'LUNGLEI' 'MAMIT'
 'SAIHA' 'DIMAPUR' 'KOHIMA' 'MOKOKCHUNG' 'MON' 'PHEK' 'TUENSANG' 'WOKHA'
 'ZUNHEBOTO' 'ANUGUL' 'BALANGIR' 'BALESHWAR' 'BARGARH' 'BHADRAK' 'BOUDH'
 'CUTTACK' 'DEOGARH' 'DHENKANAL' 'GAJAPATI' 'GANJAM' 'JAGATSINGHAPUR'
 'JAJAPUR' 'JHARSUGUDA' 'KALAHANDI' 'KANDHAMAL' 'KENDRAPARA' 'KENDUJHAR'
 'KHORDHA' 'KORAPUT' 'MALKANGIRI' 'MAYURBHANJ' 'NABARANGPUR' 'NAYAGARH'
 'NUAPADA' 'RAYAGADA' 'SAMBALPUR' 'SONEPUR' 'SUNDARGARH' 'PURI' 'MAHE'
 'PONDICHERRY' 'KARAIKAL' 'YANAM' 'AMRITSAR' 'BATHINDA' 'FARIDKOT'
 'FATEHGARH SAHIB' 'FIROZEPUR' 'HOSHIARPUR' 'JALANDHAR' 'KAPURTHALA'
 'LUDHIANA' 'MOGA' 'MUKTSAR' 'NAWANSHAHR' 'PATIALA' 'RUPNAGAR' 'SANGRUR'
 'MANSA' 'GURDASPUR' 'AJMER' 'ALWAR' 'BANSWARA' 'BARAN' 'BHARATPUR'
 'BHILWARA' 'BIKANER' 'BUNDI' 'CHITTORGARH' 'DAUSA' 'DHOLPUR' 'DUNGARPUR'
 'GANGANAGAR' 'HANUMANGARH' 'JAIPUR' 'JAISALMER' 'JALORE' 'JHALAWAR'
 'KARAULI' 'KOTA' 'NAGAUR' 'PALI' 'RAJSAMAND' 'SAWAI MADHOPUR' 'SIKAR'
 'SIROHI' 'TONK' 'UDAIPUR' 'BARMER' 'CHURU' 'JHUNJHUNU' 'JODHPUR'
 'PRATAPGARH' 'EAST DISTRICT' 'NORTH DISTRICT' 'SOUTH DISTRICT'
 'WEST DISTRICT' 'COIMBATORE' 'DHARMAPURI' 'DINDIGUL' 'ERODE'
 'KANNIYAKUMARI' 'KARUR' 'KRISHNAGIRI' 'NAGAPATTINAM' 'NAMAKKAL'
 'PERAMBALUR' 'SALEM' 'THANJAVUR' 'THE NILGIRIS' 'THENI' 'THIRUVARUR'
 'TIRUCHIRAPPALLI' 'TIRUNELVELI' 'VIRUDHUNAGAR' 'CUDDALORE' 'KANCHIPURAM'
 'MADURAI' 'PUDUKKOTTAI' 'RAMANATHAPURAM' 'SIVAGANGA' 'THIRUVALLUR'
 'THOOTHUKUDI' 'TIRUVANNAMALAI' 'VELLORE' 'VILLUPURAM' 'DHALAI'
 'NORTH TRIPURA' 'SOUTH TRIPURA' 'WEST TRIPURA' 'AGRA' 'ALIGARH'
 'ALLAHABAD' 'AMBEDKAR NAGAR' 'AMROHA' 'AURAIYA' 'AZAMGARH' 'BAGHPAT'
 'BAHRAICH' 'BALLIA' 'BALRAMPUR' 'BANDA' 'BARABANKI' 'BAREILLY' 'BASTI'
 'BIJNOR' 'BUDAUN' 'BULANDSHAHR' 'CHANDAULI' 'CHITRAKOOT' 'DEORIA' 'ETAH'
 'ETAWAH' 'FAIZABAD' 'FARRUKHABAD' 'FATEHPUR' 'FIROZABAD'
 'GAUTAM BUDDHA NAGAR' 'GHAZIABAD' 'GHAZIPUR' 'GONDA' 'GORAKHPUR' 'HARDOI'
 'HATHRAS' 'JALAUN' 'JAUNPUR' 'JHANSI' 'KANNAUJ' 'KANPUR DEHAT'
 'KANPUR NAGAR' 'KAUSHAMBI' 'KHERI' 'KUSHI NAGAR' 'LALITPUR' 'LUCKNOW'
 'MAHARAJGANJ' 'MAHOBA' 'MAINPURI' 'MATHURA' 'MAU' 'MEERUT' 'MIRZAPUR'
 'MORADABAD' 'MUZAFFARNAGAR' 'PILIBHIT' 'RAE BARELI' 'RAMPUR' 'SAHARANPUR'
 'SANT KABEER NAGAR' 'SANT RAVIDAS NAGAR' 'SHAHJAHANPUR' 'SHRAVASTI'
 'SIDDHARTH NAGAR' 'SITAPUR' 'SONBHADRA' 'SULTANPUR' 'UNNAO' 'VARANASI'
 'CHAMOLI' 'CHAMPAWAT' 'DEHRADUN' 'HARIDWAR' 'NAINITAL' 'PAURI GARHWAL'
 'PITHORAGARH' 'RUDRA PRAYAG' 'TEHRI GARHWAL' 'UDAM SINGH NAGAR'
 'UTTAR KASHI' 'ALMORA' 'BAGESHWAR' '24 PARAGANAS NORTH'
 '24 PARAGANAS SOUTH' 'BANKURA' 'BIRBHUM' 'COOCHBEHAR' 'DARJEELING'
 'DINAJPUR DAKSHIN' 'DINAJPUR UTTAR' 'HOOGHLY' 'HOWRAH' 'JALPAIGURI'
 'MALDAH' 'MEDINIPUR EAST' 'MEDINIPUR WEST' 'MURSHIDABAD' 'NADIA'
 'PURBA BARDHAMAN' 'PURULIA' 'ANJAW' 'BAKSA' 'CHIRANG' 'KAMRUP METRO'
 'UDALGURI' 'NARAYANPUR' 'NORTH GOA' 'SOUTH GOA' 'MEWAT' 'PALGHAR'
 'LAWNGTLAI' 'SERCHHIP' 'S' 'TARN TARAN' 'Andaman and Nicobar Islands'
 'DELHI_TOTAL' 'TAPI' 'PALWAL' 'REASI' 'SAMBA' 'KISHTWAR' 'RAMBAN'
 'KULGAM' 'BANDIPORA' 'GANDERBAL' 'SHOPIAN' 'KHUNTI' 'RAMGARH'
 'RAMANAGARA' 'CHIKBALLAPUR' 'ALIRAJPUR' 'SINGRAULI' 'KIPHIRE' 'LONGLENG'
 'PEREN' 'BARNALA' 'TIRUPPUR' 'ARIYALUR' 'KASGANJ' 'BALOD' 'BALODA BAZAR'
 'BEMETARA' 'GARIYABAND' 'KONDAGAON' 'MUNGELI' 'SUKMA' 'SURAJPUR' 'YADGIR'
 'FAZILKA' 'PATHANKOT' 'GOMATI' 'KHOWAI' 'SEPAHIJALA' 'UNAKOTI' 'AMETHI'
 'HAPUR' 'SAMBHAL' 'SHAMLI' 'KRA DAADI' 'LONGDING' 'NAMSAI' 'SIANG' 'DIU'
 'DAMAN' 'ARAVALLI' 'BOTAD' 'CHHOTAUDEPUR' 'GIR SOMNATH' 'MAHISAGAR'
 'DEVBHUMI DWARKA' 'MORBI' 'CHARKI DADRI' 'AGAR MALWA' 'NORTH GARO HILLS'
 'SOUTH WEST GARO HILLS' 'SOUTH WEST KHASI HILLS' 'WEST JAINTIA HILLS'
 'ALIPURDUAR' 'KAMLE' 'LOWER SIANG' 'MUMBAI SUBURBAN' 'CHENNAI'
 'BHADRADRI' 'JAGITIAL' 'JANGOAN' 'JAYASHANKAR' 'JOGULAMBA' 'KAMAREDDY'
 'KOMARAM BHEEM ASIFABAD' 'MAHABUBABAD' 'MANCHERIAL' 'MEDCHAL' 'MULUGU'
 'NAGARKURNOOL' 'NARAYANAPET' 'NIRMAL' 'PEDDAPALLI' 'RAJANNA' 'SANGAREDDY'
 'SIDDIPET' 'SURYAPET' 'VIKARABAD' 'WANAPARTHY' 'WARANGAL URBAN' 'YADADRI'
 'JHARGRAM' 'PASCHIM BARDHAMAN' 'KALIMPONG' 'LEPARADA' 'PAKKE KESSANG'
 'SHI YOMI' 'BISWANATH' 'CHARAIDEO' 'HOJAI' 'MAJULI'
 'SOUTH SALMARA MANCACHAR' 'WEST KARBI ANGLONG' 'GAURELLA-PENDRA-MARWAHI'
 'BAGALKOTE' 'BALLARI' 'BELAGAVI' 'CHAMARAJANAGARA' 'CHIKKABALLAPURA'
 'CHIKKAMAGALURU' 'DAKSHINA KANNADA' 'MYSURU' 'SHIVAMOGGA' 'TUMAKURU'
 'UTTARA KANNADA' 'VIJAYAPURA' 'KALABURAGI' 'YADAGIRI' 'NIWARI'
 'SHAHID BHAGAT SINGH NAGAR' 'TUTICORIN' 'KALLAKURICHI' 'TENKASI'
 'TIRUPATHUR' 'CHENGALPATTU' 'RANIPET' 'HANUMAKONDA' 'MEDCHAL MALKAJGIRI'
 'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU' 'HYDERABAD' 'MUMBAI']

In [7]:
df['Area Units'].value_counts()

Area Units
Hectare    345407
Name: count, dtype: int64

In [8]:
df['Production Units'].value_counts()

Production Units
Tonnes    331686
Bales      10794
Nuts        2927
Name: count, dtype: int64

In [9]:
df[df['Production Units'] == 'Nuts']['Crop'].value_counts()

Crop
Coconut    2927
Name: count, dtype: int64

In [10]:
def unit_standardization(df):

  if df['Production Units'] == 'Nuts':
    return np.round(df['Production']/500,0)
  elif df['Production Units'] == 'Tonnes':
    return df['Production']
  else:
    return np.round(df['Production']/4.59296,0)

In [11]:
df['New Production'] = df.apply(unit_standardization,axis=1)
df.sample(5)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,New Production
287255,Madhya Pradesh,ANUPPUR,Onion,2019-20,Whole Year,1453.43,Hectare,34129.02,Tonnes,23.481709,34129.02
309716,Delhi,Delhi,Rice,1999-00,Kharif,8105.00,Hectare,15279.00,Tonnes,1.885133,15279.00
246757,Kerala,PALAKKAD,Banana,2016-17,Whole Year,15199.00,Hectare,139231.00,Tonnes,9.160537,139231.00
234160,Chhattisgarh,RAJNANDGAON,Jowar,2018-19,Whole Year,27.00,Hectare,23.00,Tonnes,0.851852,23.00
68393,Meghalaya,WEST KHASI HILLS,Tapioca,2006-07,Kharif,638.00,Hectare,3373.00,Tonnes,5.286834,3373.00

In [12]:
df[df['Production Units'] == 'Nuts']

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,New Production
20,Andaman and Nicobar Islands,NICOBARS,Coconut,2001-02,Whole Year,18190.00,Hectare,64430000.0,Nuts,3542.056075,128860.0
21,Andaman and Nicobar Islands,NICOBARS,Coconut,2002-03,Whole Year,18240.00,Hectare,67490000.0,Nuts,3700.109649,134980.0
22,Andaman and Nicobar Islands,NICOBARS,Coconut,2003-04,Whole Year,18284.74,Hectare,68580000.0,Nuts,3750.668590,137160.0
23,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Coconut,2001-02,Whole Year,7015.00,Hectare,25250000.0,Nuts,3599.429793,50500.0
24,Andaman and Nicobar Islands,SOUTH ANDAMANS,Coconut,2002-03,Whole Year,7060.00,Hectare,26830000.0,Nuts,3800.283286,53660.0
...,...,...,...,...,...,...,...,...,...,...,...
343479,West Bengal,PURBA BARDHAMAN,Coconut,2000-01,Whole Year,1952.00,Hectare,28460200.0,Nuts,14580.020492,56920.0
343480,West Bengal,PURULIA,Coconut,1997-98,Whole Year,17.00,Hectare,340000.0,Nuts,20000.000000,680.0
343481,West Bengal,PURULIA,Coconut,1998-99,Whole Year,20.00,Hectare,310000.0,Nuts,15500.000000,620.0
343482,West Bengal,PURULIA,Coconut,1999-00,Whole Year,20.00,Hectare,290000.0,Nuts,14500.000000,580.0
343483,West Bengal,PURULIA,Coconut,2000-01,Whole Year,27.00,Hectare,364500.0,Nuts,13500.000000,729.0

In [13]:
df = df.drop(columns=['Production','Production Units','Area Units'])
df.head()

,State,District,Crop,Year,Season,Area,Yield,New Production
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,1.643541,2061.0
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,1.655803,2083.0
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,1.209358,1525.0
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,1.690000,5239.0
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,1.696296,5267.0

In [14]:
#Which crop is most common choice in India?

df['Crop'].value_counts().head(5)

Crop
Rice                 21611
Maize                20507
Moong(Green Gram)    15101
Urad                 14581
Sesamum              13049
Name: count, dtype: int64

In [16]:
unique_states_list = df['State'].unique()
unique_states_list

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Telangana', 'Laddakh'], dtype=object)

## Get the statewise total crop production

In [17]:
total_production = []

for st in unique_states_list:
  total_production.append(df.loc[df['State'] == st,'New Production'].sum())

In [20]:
crop_production_df = pd.DataFrame(
    {
        'State' : unique_states_list,
        'Total Crop Production' : total_production
    }
)

In [34]:
crop_production_df.sort_values('Total Crop Production', ascending=False).head(10)

             State  Total Crop Production
31   Uttar Pradesh    4442548838.69999981
19     Maharashtra    1790382270.50000000
16       Karnataka    1187930985.19676995
29      Tamil Nadu    1176880607.87900019
1   Andhra Pradesh     867700696.00000000
18  Madhya Pradesh     812939466.76999998
26          Punjab     754457911.00000000
33     West Bengal     741793775.70400000
11         Gujarat     695512467.46000004
27       Rajasthan     568764641.50000000

In [33]:
pd.set_option('display.float_format', '{:.8f}'.format)

## Which state is the highest producer of Maize between 1997 and 2022

In [25]:
maize_df = df[df['Crop'] == 'Maize']

maize_states_list = maize_df['State'].unique()
maize_states_list

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Delhi',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
       'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura',
       'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
       'Andaman and Nicobar Islands', 'Kerala', 'Telangana'], dtype=object)

In [27]:
total_maize_production = []

for st in maize_states_list:
  total_maize_production.append(maize_df.loc[maize_df['State'] == st,'New Production'].sum())

In [28]:
maize_production_df = pd.DataFrame(
    {
        'State' : maize_states_list,
        'Total Crop Production' : total_maize_production
    }
)

In [30]:
maize_production_df.sort_values('Total Crop Production', ascending=False).head(10)

             State  Total Crop Production
14       Karnataka             69082846.0
0   Andhra Pradesh             55285104.0
3            Bihar             48767397.0
15  Madhya Pradesh             46292906.0
16     Maharashtra             35732125.0
23       Rajasthan             33079191.0
27   Uttar Pradesh             30280149.0
25      Tamil Nadu             25280990.0
32       Telangana             18931921.0
9          Gujarat             15093574.0

# Best Year for Agriculture

In [35]:
unique_year_list = df['Year'].unique()

In [36]:
yearly_production = []

for yr in unique_year_list:
  yearly_production.append(df.loc[df['Year'] == yr, 'New Production'].sum())

In [38]:
yearly_production_df = pd.DataFrame(
    {
        'year' : unique_year_list,
        'total_crop_production' : yearly_production
    }
)

In [40]:
yearly_production_df.sort_values('total_crop_production',ascending=False).head()

       year  total_crop_production
18  2019-20     886266820.39227676
17  2018-19     870266605.41799998
16  2017-18     856215047.28299999
12  2013-14     783655954.26399994
15  2016-17     780278840.17799997

In [41]:
yearly_production_df.sort_values('total_crop_production',ascending=True).head()

       year  total_crop_production
19  2020-21      10177226.00000000
21  1997-98     457532079.00000000
3   2004-05     531255394.16463727
1   2002-03     544492594.62137008
22  1998-99     552361276.00000000