In [43]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [44]:
df = pd.read_csv('/content/drive/MyDrive/Daksh_Gururkul_IITG_May_2025/08_Pandas/mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [46]:
df['origin'].value_counts()

origin
1    249
3     79
2     70
Name: count, dtype: int64

In [47]:
df[df['origin'] == 2]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104.0,95,2375,17.5,70,2,saab 99e
23,26.0,4,121.0,113,2234,12.5,70,2,bmw 2002
...,...,...,...,...,...,...,...,...,...
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
359,28.1,4,141.0,80,3230,20.4,81,2,peugeot 505s turbo diesel
360,30.7,6,145.0,76,3160,19.6,81,2,volvo diesel
375,36.0,4,105.0,74,1980,15.3,82,2,volkswagen rabbit l
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup

In [48]:
#pd.to_numeric(df['horsepower'])

In [49]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [50]:
df[df['horsepower'] == '?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [51]:
df1 = df[df['horsepower'] != '?']
df1 = df1[df1['cylinders'] == 4]
replaced_hp = np.round(pd.to_numeric(df1['horsepower']).mean(),2)
replaced_hp

np.float64(78.28)

In [52]:
df['horsepower'] = df['horsepower'].replace('?',replaced_hp)

In [53]:
df['horsepower'] = pd.to_numeric(df['horsepower'])

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB

In [55]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [56]:
df = df.drop('name',axis=1)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,1
1,15.0,8,350.0,165.0,3693,11.5,70,1
2,18.0,8,318.0,150.0,3436,11.0,70,1
3,16.0,8,304.0,150.0,3433,12.0,70,1
4,17.0,8,302.0,140.0,3449,10.5,70,1

In [58]:
df.groupby('model_year').mean()

,mpg,cylinders,displacement,horsepower,weight,acceleration,origin
model_year,,,,,,,
70,17.689655,6.758621,281.413793,147.827586,3372.793103,12.948276,1.310345
71,21.250000,5.571429,209.750000,106.010000,2995.428571,15.142857,1.428571
72,18.714286,5.821429,218.375000,120.178571,3237.714286,15.125000,1.535714
73,17.100000,6.375000,256.875000,130.475000,3419.025000,14.312500,1.375000
74,22.703704,5.259259,171.740741,93.640000,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,101.066667,3176.800000,16.050000,1.466667
76,21.573529,5.647059,197.794118,101.117647,3078.735294,15.941176,1.470588
77,23.375000,5.464286,191.392857,105.071429,2997.357143,15.435714,1.571429
78,24.061111,5.361111,177.805556,99.694444,2861.805556,15.805556,1.611111
79,25.093103,5.827586,206.689655,101.206897,3055.344828,15.813793,1.275862
80,33.696552,4.137931,115.827586,77.536552,2436.655172,16.934483,2.206897
81,30.334483,4.620690,135.310345,80.940690,2522.931034,16.306897,1.965517
82,31.709677,4.193548,128.870968,81.363871,2453.548387,16.638710,1.645161

In [60]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
horsepower   count    29.000000    28.000000    28.000000    40.000000
             mean    147.827586   106.010000   120.178571   130.475000
             std      53.734844    38.233394    41.121368    46.412304
             min      46.000000    60.000000    54.000000    46.000000
             25%      95.000000    77.710000    86.750000    93.250000
             50%     150.000000    92.500000   104.500000   129.500000
             75%     198.000000   120.000000   150.750000   160.250000
             max     225.000000   180.000000   208.000000   230.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
horsepower   count    27.000000    30.000000    34.000000    28.000000
             mean     93.640000   101.066667   101.117647   105.071429
             std      29.271684    26.577062    32.430592    36.095479
             min      52.000000    53.000000    52.000000    58.000000
             25%      75.000000    84.250000    78.250000    78.000000
             50%      83.000000    97.000000    93.500000    97.500000
             75%     102.500000   110.000000   120.000000   115.000000
             max     150.000000   170.000000   180.000000   190.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
horsepower   count    36.000000    29.000000    29.000000    29.000000
             mean     99.694444   101.206897    77.536552    80.940690
             std      28.436214    28.455955    17.513187    17.786729
             min      48.000000    65.000000    48.000000    58.000000
             25%      82.500000    77.000000    67.000000    65.000000
             50%      97.000000    90.000000    75.000000    76.000000
             75%     116.250000   125.000000    90.000000    88.000000
             max     165.000000   155.000000   132.000000   120.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
horsepower   count    31.000000
             mean     81.363871
             std      13.085990
             min      52.000000
             25%      70.000000
             50%      84.000000
             75%      88.000000
             max     112.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

# Multiple Columns

In [63]:
cylwise = df.groupby(['model_year','cylinders']).mean()
cylwise

                            mpg  displacement  horsepower       weight  \
model_year cylinders
70         4          25.285714    107.000000   87.714286  2292.571429
           6          20.500000    199.000000   91.750000  2710.500000
           8          14.111111    367.555556  183.666667  3940.055556
71         4          27.461538    101.846154   77.636923  2056.384615
           6          18.000000    243.375000   98.875000  3171.875000
           8          13.428571    371.714286  166.857143  4537.714286
72         3          19.000000     70.000000   97.000000  2330.000000
           4          23.428571    111.535714   85.142857  2382.642857
           8          13.615385    344.846154  159.692308  4228.384615
73         3          18.000000     70.000000   90.000000  2124.000000
           4          22.727273    109.272727   82.909091  2338.090909
           6          19.000000    212.250000  102.125000  2917.125000
           8          13.200000    365.250000  170.000000  4279.050000
74         4          27.800000     96.533333   74.000000  2151.466667
           6          17.857143    230.428571   98.325714  3320.000000
           8          14.200000    315.200000  146.000000  4438.400000
75         4          25.250000    114.833333   84.916667  2489.250000
           6          17.583333    233.750000   96.750000  3398.333333
           8          15.666667    330.500000  142.000000  4108.833333
76         4          26.766667    106.333333   75.600000  2306.600000
           6          20.000000    221.400000   98.700000  3349.600000
           8          14.666667    324.000000  146.333333  4064.666667
77         3          21.500000     80.000000  110.000000  2720.000000
           4          29.107143    106.500000   78.785714  2205.071429
           6          19.500000    220.400000  102.000000  3383.000000
           8          16.000000    335.750000  152.375000  4177.500000
78         4          29.576471    112.117647   79.705882  2296.764706
           5          20.300000    131.000000  103.000000  2830.000000
           6          19.066667    213.250000  109.833333  3314.166667
           8          19.050000    300.833333  135.500000  3563.333333
79         4          31.525000    113.583333   75.750000  2357.583333
           5          25.400000    183.000000   77.000000  3530.000000
           6          22.950000    205.666667  105.000000  3025.833333
           8          18.630000    321.400000  131.900000  3862.900000
80         3          23.700000     70.000000  100.000000  2420.000000
           4          34.612000    111.000000   74.382400  2360.080000
           5          36.400000    121.000000   67.000000  2950.000000
           6          25.900000    196.500000  111.000000  3145.500000
81         4          32.814286    108.857143   73.203810  2275.476190
           6          23.428571    184.000000  100.714286  3093.571429
           8          26.600000    350.000000  105.000000  3725.000000
82         4          32.071429    118.571429   79.117143  2402.321429
           6          28.333333    225.000000  102.333333  2931.666667

                      acceleration    origin
model_year cylinders
70         4             16.000000  2.285714
           6             15.500000  1.000000
           8             11.194444  1.000000
71         4             16.961538  1.923077
           6             14.750000  1.000000
           8             12.214286  1.000000
72         3             13.500000  3.000000
           4             17.214286  1.928571
           8             13.000000  1.000000
73         3             13.500000  3.000000
           4             17.136364  2.000000
           6             15.687500  1.250000
           8             12.250000  1.000000
74         4             16.400000  2.200000
           6             16.857143  1.000000
           8             14.700000  1.000000
75         4             15.833333  2.166667
           6             17.708333  1.000000
           8             13.166667  1.000000
76         4             16.866667  1.866667
           6             17.000000  1.300000
           8             13.222222  1.000000
77         3             13.500000  3.000000
           4             16.064286  1.857143
           6             16.900000  1.400000
           8             13.662500  1.000000
78         4             16.282353  2.117647
           5             15.900000  2.000000
           6             16.391667  1.166667
           8             13.266667  1.000000
79         4             15.991667  1.583333
           5             20.100000  2.000000
           6             15.433333  1.000000
           8             15.400000  1.000000
80         3             12.500000  3.000000
           4             17.144000  2.200000
           5             19.900000  2.000000
           6             15.050000  2.000000
81         4             16.466667  2.095238
           6             15.442857  1.714286
           8             19.000000  1.000000
82         4             16.703571  1.714286
           6             16.033333  1.000000

In [66]:
df1.index

Index([ 14,  18,  19,  20,  21,  22,  23,  29,  30,  31,
       ...
       385, 388, 390, 391, 392, 393, 394, 395, 396, 397],
      dtype='int64', length=199)

In [64]:
cylwise.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [70]:
cylwise.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [71]:
cylwise.index.names

FrozenList(['model_year', 'cylinders'])

In [72]:
cylwise.loc[(74,6)]

mpg               17.857143
displacement     230.428571
horsepower        98.325714
weight          3320.000000
acceleration      16.857143
origin             1.000000
Name: (74, 6), dtype: float64

In [73]:
cylwise.loc[[75,78]]

                            mpg  displacement  horsepower       weight  \
model_year cylinders
75         4          25.250000    114.833333   84.916667  2489.250000
           6          17.583333    233.750000   96.750000  3398.333333
           8          15.666667    330.500000  142.000000  4108.833333
78         4          29.576471    112.117647   79.705882  2296.764706
           5          20.300000    131.000000  103.000000  2830.000000
           6          19.066667    213.250000  109.833333  3314.166667
           8          19.050000    300.833333  135.500000  3563.333333

                      acceleration    origin
model_year cylinders
75         4             15.833333  2.166667
           6             17.708333  1.000000
           8             13.166667  1.000000
78         4             16.282353  2.117647
           5             15.900000  2.000000
           6             16.391667  1.166667
           8             13.266667  1.000000

In [74]:
df.groupby('model_year').agg(
    {
        'mpg' : ['median','mean'],
        'displacement' : ['std','max','var']
    }
)

              mpg            displacement
           median       mean          std    max           var
model_year
70          16.00  17.689655   124.421380  455.0  15480.679803
71          19.00  21.250000   115.102410  400.0  13248.564815
72          18.50  18.714286   123.781964  429.0  15321.974537
73          16.00  17.100000   121.722085  455.0  14816.266026
74          24.00  22.703704    92.601127  350.0   8574.968661
75          19.50  20.266667    87.669730  400.0   7685.981609
76          21.00  21.573529    94.422256  351.0   8915.562389
77          21.75  23.375000   107.813742  400.0  11623.802910
78          20.70  24.061111    76.012713  318.0   5777.932540
79          23.90  25.093103    96.307581  360.0   9275.150246
80          32.70  33.696552    33.744914  225.0   1138.719212
81          31.60  30.334483    58.387929  350.0   3409.150246
82          32.00  31.709677    39.352037  262.0   1548.582796