In [47]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Python DateTime Library

In [48]:
from datetime import datetime

In [49]:
my_year = 2025
my_month = 7
my_day = 24
my_hour = 21
my_min = 15
my_sec = 11

In [50]:
my_date = datetime(my_year,my_month,my_day,my_hour,my_min, my_sec)

In [51]:
my_date

datetime.datetime(2025, 7, 24, 21, 15, 11)

In [52]:
my_date.weekday()

3

In [53]:
my_date.hour

21

In [54]:
my_date.isoweekday()

4

# pandas

In [55]:
myser = pd.Series(['Nov 3, 2025','2025-07-24',None])
myser

0    Nov 3, 2025
1     2025-07-24
2           None
dtype: object

In [56]:
myser[0]

'Nov 3, 2025'

In [57]:
sample = pd.to_datetime(myser,format = 'mixed')

In [58]:
sample[0]

Timestamp('2025-11-03 00:00:00')

In [59]:
demo_date = '22-12-2025'

In [60]:
pd.to_datetime(demo_date,dayfirst=True)

Timestamp('2025-12-22 00:00:00')

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

In [61]:
stylish_date = '24**July&&2025'

In [62]:
pd.to_datetime(stylish_date,format='%d**%B&&%Y')

Timestamp('2025-07-24 00:00:00')

In [63]:
strange_date = '24th of Dec * 2025'

In [64]:
pd.to_datetime(strange_date,format='%dth of %b * %Y')

Timestamp('2025-12-24 00:00:00')

# Data

In [65]:
sales = pd.read_csv('/content/drive/MyDrive/Daksh_Gururkul_IITG_May_2025/08_Pandas/RetailSales_BeerWineLiquor.csv')
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [66]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    object
 1   MRTSSM4453USN  340 non-null    int64
dtypes: int64(1), object(1)
memory usage: 5.4+ KB

In [67]:
sales.iloc[0]['DATE']

'1992-01-01'

In [68]:
sales['DATE'] = pd.to_datetime(sales['DATE'])
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[ns]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 5.4 KB

In [69]:
sales.iloc[0]['DATE']

Timestamp('1992-01-01 00:00:00')

In [70]:
#sales = sales.set_index('DATE')
#sales.info()

.dt method calls

In [73]:
sales['is_leap'] = sales['DATE'].dt.is_leap_year
sales.head()

        DATE  MRTSSM4453USN  is_leap
0 1992-01-01           1509     True
1 1992-02-01           1541     True
2 1992-03-01           1597     True
3 1992-04-01           1675     True
4 1992-05-01           1822     True

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html

In [79]:
sales['Month'] = sales['DATE'].dt.month
sales.sample(5)

          DATE  MRTSSM4453USN  is_leap  Month
335 2019-12-01           6630    False     12
333 2019-10-01           4913    False     10
229 2011-02-01           2984    False      2
233 2011-06-01           3551    False      6
62  1997-03-01           1853    False      3

In [82]:
sales['Year'] = sales['DATE'].dt.year
sales.sample(5)

          DATE  MRTSSM4453USN  is_leap  Month  Year
274 2014-11-01           4103    False     11  2014
271 2014-08-01           4219    False      8  2014
219 2010-04-01           3310    False      4  2010
280 2015-05-01           4335    False      5  2015
143 2003-12-01           3654    False     12  2003

In [81]:
sales[['MRTSSM4453USN','Month']].groupby('Month').mean()

       MRTSSM4453USN
Month
1        2600.310345
2        2608.862069
3        2913.827586
4        2902.206897
5        3087.607143
6        3063.535714
7        3200.107143
8        3117.142857
9        2946.750000
10       3040.178571
11       3166.714286
12       4223.821429

In [83]:
sales[['MRTSSM4453USN','Year']].groupby('Year').mean()

      MRTSSM4453USN
Year
1992    1807.250000
1993    1794.833333
1994    1841.750000
1995    1833.916667
1996    1929.750000
1997    2006.750000
1998    2115.166667
1999    2206.333333
2000    2375.583333
2001    2468.416667
2002    2491.166667
2003    2539.083333
2004    2682.416667
2005    2797.250000
2006    3001.333333
2007    3177.333333
2008    3292.000000
2009    3353.750000
2010    3450.083333
2011    3532.666667
2012    3697.083333
2013    3839.666667
2014    4023.833333
2015    4212.500000
2016    4434.416667
2017    4602.666667
2018    4830.666667
2019    4972.750000
2020    4922.500000